name: surf
services:
  - name: web
    github:
      repo: thinkverse/surf
      branch: main
      deploy_on_push: true
      run_command: php artisan migrate --force ; heroku-php-apache2 public/
    envs:
      - key: APP_URL
        value: ${APP_URL}
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        value: "base64:zexFqn1eQjw1Weqx1Qp6YFX6yloRsoElqxWbSJv39N4="
        type: SECRET
      - key: LOG_CHANNEL
        scope: RUN_TIME
        value: "stack"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "debug"
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_DATABASE
        value: ${db.DATABASE}
      - key: DB_USERNAME
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
    databases:
      - name: db
jobs:
  - name: migrate
    kind: POST_DEPLOY
    github:
      repo: thinkverse/surf
      branch: main
      deploy_on_push: true
    run_command: php artisan migrate --seed ; php artisan storage:link
    envs:
      - key: APP_NAME
        scope: RUN_TIME
        value: Suft
      - key: APP_ENV
        scope: RUN_TIME
        value: production
      - key: APP_KEY
        scope: RUN_TIME
        value: "base64:zexFqn1eQjw1Weqx1Qp6YFX6yloRsoElqxWbSJv39N4="
      - key: APP_DEBUG
        scope: RUN_TIME
        value: "false"
      - key: APP_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: LOG_CHANNEL
        scope: RUN_TIME
        value: "stack"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "debug"
      - key: DB_CONNECTION
        value: "pgsql"
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_DATABASE
        value: ${db.DATABASE}
      - key: DB_USERNAME
        value: ${db.USERNAME}
        type: SECRET
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
        type: SECRET
